WAV-2592: API to fetch sim total usages: Manually update the external api doc
AxonMobile/SimCardApiDocs pull request #26
Opened 2022-12-28 13:47 UTC by lizozavr

2023-01-02 14:38 UTC, clissau requested changes
Minor changes requested.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +Request body contains GetSimCardUsageDTO with such fields:
Add blank line between header and body.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
>  | imei        | String            | The observed IMEI number for the device generating the usage. |
Suggestion to add a `<br>` in description text, to create multiline text. With current text length I get a scroll bar at the bottom.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| icc             | String                                                   | The unique identifier for the SIM card generating the usage. |
Suggestion to add a `<br>` in description text, to create multiline text. With current text length I get a scroll bar at the bottom.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| icc             | String                                                   | The unique identifier for the SIM card generating the usage. |
Suggestion to add a `<br>` in description text, to create multiline text. With current text length I get a scroll bar at the bottom.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| icc             | String                                                   | The unique identifier for the SIM card generating the usage.
Suggestion to add a `<br>` in description text, to create multiline text. With current text length I get a scroll bar at the bottom.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| duration        | Number                                                   | Duration of the call measured in seconds, the result disregards network connection time. i.e. Only the billed call durat
Suggestion to add a `<br>` in description text, to create multiline text. With current text length I get a scroll bar at the bottom.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +Ger the total data usage of a specific SIM Card for a given **period** can be accessed by using the following URL:
Typo in `Ger`.
`Card` is previously written in small letters.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| endDateTime   | LocalDateTime | End date and time of period for getting sim card usage   |
Please write `SIM` capitalized.

2023-01-02 14:38 UTC, clissau commented on docs/api/sim-card-usage.md
> +| sumTotalBytes | Long   | The total data usage sum of bytes of sim card               |
Please write `SIM` capitalized.

2023-01-02 16:05 UTC, haodengwavely requested changes

2023-01-02 16:05 UTC, haodengwavely commented on docs/api/sim-card-usage.md
> +| startDateTime | LocalDateTime | Start date and time of period for getting sim card usage |
LocalDateTime is java data type. It should be a String in json request.

2023-01-04 07:34 UTC, haodengwavely approved these changes

2023-01-04 07:45 UTC, clissau approved these changes

2023-01-04 07:46 UTC, merged